import { IMAGES } from "../constants";

const plants = [
  {
    title: "Spider Plant",
    image: IMAGES.SpiderPlant,
    desc: "Spider plants are popular houseplants with long, arching, green or variegated leaves growing from a central rosette. They produce small white flowers and distinctive plantlets on trailing stems, which are easy to propagate. Known for their air-purifying qualities, they thrive in a wide range of environments. Spider plants are especially suited for beginners due to their adaptability and resilience.",
    price: "₹179",
    type: ["INDOOR", "POPULAR"],
    favourite: false,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Snake Plant",
    image: IMAGES.SnakePlant,
    desc: "Snake plants feature tall, stiff, sword-shaped leaves with green and yellow variegation, growing upright from the soil. They are exceptionally low-maintenance, requiring minimal light and water. Snake plants are known for their air-purifying capabilities, removing toxins from indoor spaces. Their architectural form makes them ideal for modern interiors.",
    price: "₹299",
    type: ["INDOOR", "POPULAR"],
    favourite: false,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Peace Lily",
    image: IMAGES.PeaceLily,
    desc: "Peace lilies are evergreen perennials with glossy, dark-green leaves and striking white spathes. They thrive in shady indoor environments and require little care. Peace lilies are excellent at removing airborne pollutants. Despite their elegance, they are mildly toxic to pets, so placement should be considered carefully.",
    price: "₹349",
    type: ["INDOOR"],
    favourite: true,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Aloe Vera",
    image: IMAGES.AloeVera,
    desc: "Aloe vera is a succulent with thick, fleshy leaves filled with medicinal gel. It thrives in arid conditions and prefers bright, indirect light. Commonly used for burns and skincare, it's a staple in many households. Aloe also produces tall yellow flowers and is highly drought-tolerant.",
    price: "₹199",
    type: ["INDOOR", "OUTDOOR"],
    favourite: false,
    addToCart: true,
    quantity: 1,
  },
  {
    title: "Chinese Evergreen",
    image: IMAGES.ChineseEvergreen,
    desc: "The Chinese evergreen is a stylish indoor plant known for its patterned, lance-shaped leaves that range from green to red tones. It's easy to grow and thrives in low light, making it ideal for offices and apartments. Occasionally, it blooms with small white spathes. Its lush foliage adds a tropical feel to any space.",
    price: "₹329",
    type: ["INDOOR"],
    favourite: false,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Money Plant",
    image: IMAGES.MoneyPlant,
    desc: "The money plant, or pothos, is a fast-growing vine with heart-shaped leaves, often variegated with gold or white. It can grow in water or soil and is highly resilient. The plant is believed to bring prosperity and good luck. It's perfect for hanging baskets or trained to climb indoor poles.",
    price: "₹149",
    type: ["INDOOR", "POPULAR"],
    favourite: true,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Cheese Plant",
    image: IMAGES.ChessePlant,
    desc: "The cheese plant, or Monstera, is known for its large, split leaves that give it a dramatic look. Native to rainforests, it prefers humid environments and indirect light. It can grow very tall indoors with support. Its tropical vibe makes it a favorite among modern interior plant lovers.",
    price: "₹399",
    type: ["INDOOR"],
    favourite: false,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "English Ivy",
    image: IMAGES.EnglishIvy,
    desc: "English Ivy is a classic trailing vine with lobed leaves, great for both indoor décor and outdoor coverage. It grows quickly and clings to surfaces using aerial roots. Ideal for hanging planters or wall shelves, it needs occasional trimming. Caution: it can be invasive outdoors and toxic if ingested.",
    price: "₹249",
    type: ["OUTDOOR", "INDOOR"],
    favourite: true,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Rubber Plant",
    image: IMAGES.RubberPlant,
    desc: "The rubber plant is a hardy indoor tree with thick, glossy leaves that can be green or variegated. It can grow several feet tall indoors with minimal care. Once a source of latex, it's now admired for its air-purifying properties. It makes a bold statement in modern homes.",
    price: "₹349",
    type: ["INDOOR"],
    favourite: false,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "ZZ Plant",
    image: IMAGES.ZZPlant,
    desc: "The ZZ plant has upright, waxy leaves and thick rhizomes that store water, making it nearly indestructible. It's perfect for low-light, low-maintenance situations. Despite its toughness, it adds a sleek, elegant vibe to indoor spaces. It’s often recommended for busy professionals.",
    price: "₹399",
    type: ["INDOOR", "POPULAR"],
    favourite: true,
    addToCart: false,
    quantity: 0,
  },
  {
    title: "Rose Plant",
    image: IMAGES.Rose,
    desc: "The rose plant is beloved for its fragrant, layered blooms in a range of colors. It requires sunlight and moderate watering to thrive outdoors. Roses are symbolic of love and beauty and bloom seasonally. Their thorns require caution, but their beauty is unmatched in gardens.",
    price: "₹249",
    type: ["OUTDOOR", "POPULAR"],
    favourite: true,
    addToCart: true,
    quantity: 2,
  },
];

export default plants;
